name: Download GTFS Files and Convert to JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  download-and-convert-gtfs:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests zipfile38 pandas

    - name: Download and convert GTFS files
      run: |
        echo "
import requests
import zipfile
import os
import pandas as pd

# URL for the GTFS zip file
url = 'http://nycferry.connexionz.net/rtt/public/utility/gtfs.aspx'
zip_file_path = 'gtfs_data.zip'

# Download the GTFS zip file
response = requests.get(url)

with open(zip_file_path, 'wb') as f:
    f.write(response.content)

# Extract the files from the zip archive
extract_folder = 'gtfs_files'
if not os.path.exists(extract_folder):
    os.makedirs(extract_folder)

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

# Convert each GTFS file into JSON
for file_name in os.listdir(extract_folder):
    file_path = os.path.join(extract_folder, file_name)
    if file_name.endswith('.txt'):  # Only process text files (GTFS files)
        df = pd.read_csv(file_path)
        json_data = df.to_json(orient='records', lines=True)  # Convert to JSON

        # Write to a JSON file
        json_file_name = f'{file_name.replace('.txt', '.json')}'
        with open(f'{extract_folder}/{json_file_name}', 'w') as json_file:
            json_file.write(json_data)
        " > download_and_convert_gtfs.py  # Write the Python script to a file

    - name: Run Python script to download and convert GTFS
      run: |
        python download_and_convert_gtfs.py  # Run the Python script to download, extract, and convert

    - name: Commit and push GTFS JSON files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update GTFS data as JSON files'
