name: Download GTFS Files and Convert to JSON

on:
  schedule:
    - cron: '0 8 * * 0'  # Run at 8:00 AM UTC every Sunday
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  download-and-convert-gtfs:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests zipfile38 pandas

    - name: Run Python script to download and convert GTFS
      run: |
        python download_and_convert_gtfs.py  # Run the Python script to download, extract, and convert

    - name: Commit and push GTFS JSON files
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update GTFS data as JSON files'
